profile = "local"

[server]
host = "0.0.0.0"
port = 8080
payload = 500

[cache]
root = "./cache"

[s3]
bucket = "gradle-cache"
region = ""
endpoint = "http://10.23.172.150:9000/"
access_key = "minioadmin"
secret_key = "minioadmin"